// REPL CLUB — Mock data (정적 데모용)
// 실서비스 전환 시 백엔드 API로 교체 예정.

window.RC_DATA = {
  config: {
    eventDate: '2026.05.08 (FRI)',
    venue: '해시드 20층',
    deadline: '21:45',
    sosPhone: '010-0000-0000',
    wifi: { ssid: 'HASHED-GUEST', pw: 'replclub2026' },
    awards: { gold: 1, silver: 1, bronze: 1, special: 6, passed: 5 },
    toiletLocation: '입구 LED 옆',
  },

  timetable: [
    { time: '18:30', label: '체크인 + 간단한 저녁 제공', link: null },
    { time: '19:10', label: '오프닝', link: null },
    { time: '19:15', label: 'Replit 본사 Keynote', link: 'https://replit-douzone-hackathon.replit.app/' },
    { time: '19:25', label: '행사 진행 안내', link: null },
    { time: '19:45', label: '빌드 타임 시작', link: null, isNow: true },
    { time: '21:45', label: '제출 마감', link: null },
    { time: '22:00', label: '상위 팀 발표', link: null },
    { time: '22:35', label: '시상식', link: null },
  ],

  replitGuide: [
    {
      title: '레플릿 회원 가입',
      desc: 'replit.com 에서 회원가입을 해주세요.\n홈 화면 우측 상단의 "Create Account" 버튼을 누르고, 이메일 또는 Google 계정으로 가입할 수 있습니다.',
      link: 'https://replit.com/',
      linkLabel: 'replit.com 바로가기 →',
    },
    {
      title: '크레딧 신청',
      desc: '레플클럽 구글폼에 본인 Replit 계정을 제출해주세요.\n행사 당일 본인 계정에 $100 상당의 Pro 구독이 지급됩니다.\n※ Luma 참가 승인 대상자에 한해 1인 1회 지급됩니다.',
      link: 'https://forms.gle/uhAnQvrqn18ZSqRq9',
      linkLabel: '구글폼 제출하기 →',
    },
    {
      title: '빌드 시작!',
      desc: '크레딧 지급이 확인되면 곧바로 프로젝트를 만들어보세요.\n대화창에서 만들고 싶은 아이디어를 설명하기만 하면, Replit이 코드·DB·배포까지 알아서 해줍니다.',
      link: null,
      linkLabel: null,
    },
    {
      title: '프로젝트 등록',
      desc: '좌측 사이드바 \'레플 보드\' 메뉴에서 본인 프로젝트를 등록해주세요.\n1인 또는 2인 팀으로 참가 가능하며, 레플 보드를 통해 1차 심사가 진행됩니다.',
      link: 'https://replclub2026.vercel.app/board.html',
      linkLabel: '레플 보드 →',
    },
    {
      title: '막힐 때 도움 받기',
      desc: '궁금한 점이 생기면 좌측 사이드바 \'질문 보드\'에 남겨주세요.\nREPL CLUB 운영팀이 단계별로 답변해드립니다.',
      link: 'https://replclub2026.vercel.app/qa.html',
      linkLabel: '질문 보드 →',
    },
  ],

  judging: {
    judges: [
      { name: 'Replit 본사', role: '글로벌 1위 바이브 코딩 플랫폼' },
      { name: 'Hashed', role: '한국 대표 블록체인·Web3 VC' },
      { name: '마켓핏랩', role: 'Replit 한국 공식 파트너' },
    ],
    process: [
      {
        title: '1차 심사',
        items: [
          '빌드 시작 약 1시간 경, 심사위원이 각 팀의 프로젝트를 검토하여 기획 내용과 구현 완성도를 확인',
          '2차 발표 심사 진출할 5팀 선정',
          '프로젝트 등록 시 "5문답"을 또렷하게 작성하시는 게 유리해요.',
        ],
      },
      {
        title: '2차 심사',
        items: [
          '1차 심사에서 선발된 5팀 발표 (3분 발표 + 1분 질의)',
          '최종 1~3위 (각 1팀), 특별상 (6팀) 선정',
          '발표 시간이 짧기 때문에 "누가 왜 쓰는가 + 오늘 진짜 동작하는 부분"을 보여주는 게 핵심이에요.',
        ],
      },
    ],
    criteria: [
      { name: '비즈니스 임팩트', weight: 40 },
      { name: '완성도', weight: 30 },
      { name: '창의성', weight: 20 },
      { name: '발표력', weight: 10 },
    ],
  },

  // 시상 단계 공개 상태 (어드민 단계별 공개 시뮬레이션)
  // 'hidden' | 'passed' | 'bronze' | 'silver' | 'gold'
  awardPhase: 'hidden',

  projects: [
    {
      id: 'p001',
      team: 'LATTE',
      tagline: '카페 사장이 매출 데이터를 말로 분석하는 도구',
      members: ['수아', '민지'],
      url: 'https://latte.replit.app',
      registeredAt: '20:14',
      comments: 3,
      award: null, // 'gold' | 'silver' | 'bronze' | 'passed' | null
      details: {
        problem: '소규모 카페 사장님들은 POS·배달앱·SNS 데이터가 흩어져 있어 한 번에 보기 어렵습니다. 매출 패턴 파악에 매주 2시간씩 들어가요.',
        target: '동네 카페 사장님 (1~2인 운영, 대시보드 도구는 부담스러운 분).',
        better: '엑셀·차트 만들지 않고 "지난주 대비 어떠냐"고 말로 묻기만 하면 답이 옵니다. 이상치도 자동으로 알려줘요.',
        mvp: '4시간 안에 — POS CSV 업로드 + 자연어 질문 + 핵심 지표 자동 답변. 배포까지.',
        progress: 'POS CSV 업로드 → 매출/원가/마진 자동 계산까지 작동. 자연어 질문은 GPT-4 호출 붙임.',
      },
    },
    {
      id: 'p002',
      team: 'BUILDLAB',
      tagline: '사내 회의 자동 요약 + 액션아이템 추출 봇',
      members: ['일렌'],
      url: 'https://buildlab.replit.app',
      registeredAt: '20:08',
      comments: 1,
      award: null,
      details: {
        problem: '회의 끝나면 모두 "정리해서 공유"라고 말만 하고 안 합니다. 액션아이템이 사라지는 게 가장 큰 손실.',
        target: '회의 많은 팀 (PM·디자이너·엔지니어 5인 이상).',
        better: 'Slack에 봇이 들어가서 회의 노트 붙이면 1분 안에 요약·액션아이템·담당자 추출.',
        mvp: '회의 텍스트 입력 → 요약 + 액션아이템 카드 출력 + 담당자 멘션.',
        progress: '입력·요약 작동. Slack 연동은 webhook까지.',
      },
    },
    {
      id: 'p003',
      team: 'DECAF',
      tagline: '매일 아침 회고를 5분 안에 끝내는 자동 정리 도구',
      members: ['미쉘', '필'],
      url: 'https://decaf.replit.app',
      registeredAt: '19:55',
      comments: 5,
      award: null,
      details: {
        problem: '회고 안 합니다. 시간 없고 양식도 매번 헷갈려서.',
        target: '주니어 ~ 미들 PM·기획자, 매일 회고하고 싶지만 못하는 분.',
        better: '오늘 한 일·내일 할 일·막힌 점만 음성으로 말하면 자동으로 정리·아카이빙.',
        mvp: '음성 입력 → 자동 분류 → 기록 + 주간 리뷰 자동 생성.',
        progress: '음성 → 텍스트 + 분류까지. 주간 리뷰는 mock UI.',
      },
    },
    {
      id: 'p004',
      team: 'PRISM',
      tagline: '프롬프트 변형 A/B 테스트 자동화 워크벤치',
      members: ['Sky', '재훈'],
      url: 'https://prism.replit.app',
      registeredAt: '20:35',
      comments: 2,
      award: null,
      details: {
        problem: '프롬프트 엔지니어링하면 변형 5~10개 만들고 손으로 비교. 너무 비효율.',
        target: 'AI 제품 만드는 개발자·PM.',
        better: '프롬프트 템플릿 입력 → 변형 자동 생성 → 동일 데이터셋 batch 평가 → 표로 비교.',
        mvp: '프롬프트 입력 → 변형 5개 생성 → 평가 → 결과 비교 테이블.',
        progress: '변형 생성·평가 작동. 결과 시각화는 단순 테이블.',
      },
    },
    {
      id: 'p005',
      team: 'BRIM',
      tagline: '이메일 답장 톤 가이드: 친절/단호/유머 자동 변환',
      members: ['지나'],
      url: 'https://brim.replit.app',
      registeredAt: '20:22',
      comments: 4,
      award: null,
      details: {
        problem: '이메일 톤 잡기 어렵습니다. 너무 딱딱하거나 너무 친절하거나.',
        target: '대외 커뮤니케이션 많은 직군 (영업·CS·PR).',
        better: '초안 입력 → 3가지 톤(친절/단호/유머) 자동 생성 → 클릭 한 번에 적용.',
        mvp: '초안 → 3톤 변환 → 복사.',
        progress: '변환·복사까지 작동. 메일 클라이언트 연동은 mock.',
      },
    },
    {
      id: 'p006',
      team: 'LOOPER',
      tagline: '주간 KPI 대시보드 자동 생성 (Slack DM 발송)',
      members: ['해리', '진'],
      url: 'https://looper.replit.app',
      registeredAt: '20:51',
      comments: 0,
      award: null,
      details: {
        problem: '주간 KPI 대시보드 사람이 매주 만들어요. 시간 낭비.',
        target: '데이터 인프라 갖춘 스타트업.',
        better: 'GA4·Mixpanel 연결 → 매주 월요일 9시에 Slack DM으로 자동 발송.',
        mvp: 'Mock 데이터 기준 대시보드 생성 + Slack 발송 시뮬레이션.',
        progress: '대시보드 생성·Slack 발송 작동.',
      },
    },
    {
      id: 'p007',
      team: 'SHIBA',
      tagline: '강아지 산책 코스 추천 앱 (반려동물 PM의 부캐)',
      members: ['보리'],
      url: 'https://shiba.replit.app',
      registeredAt: '20:42',
      comments: 7,
      award: null,
      details: {
        problem: '매일 같은 산책 코스 지겨워요. 강아지도 사람도.',
        target: '서울 사는 반려인.',
        better: '주변 1km 내 새 코스 + 다른 반려인 인기 코스 + 날씨 반영 추천.',
        mvp: '내 위치 → 추천 3코스 + 즐겨찾기.',
        progress: '위치 기반 추천·즐겨찾기 작동.',
      },
    },
    {
      id: 'p008',
      team: 'NOTEBOX',
      tagline: '메모를 GPT에게 던지면 카드 형태로 정리',
      members: ['도윤', '서아'],
      url: 'https://notebox.replit.app',
      registeredAt: '21:02',
      comments: 1,
      award: null,
      details: {
        problem: '메모 적어두지만 다시 안 봐요. 검색·분류 귀찮음.',
        target: '아이디어 메모 많이 하는 직장인·학생.',
        better: '메모 던지면 GPT가 분류·요약·태그·카드화 → 자동 인덱스.',
        mvp: '입력 → 분류·태그 → 카드 보드.',
        progress: '입력·카드화 작동.',
      },
    },
  ],

  qa: [
    {
      id: 'q001',
      author: '수아',
      time: '20:33',
      body: 'Replit 크레딧 어디서 받아요?',
      reply: {
        body: '체크인 데스크에서 받으셨던 카드 뒷면에 코드 적혀있어요! Replit 로그인 후 입력해 주세요 🙏',
        time: '20:35',
      },
    },
    {
      id: 'q002',
      author: '일렌',
      time: '20:41',
      body: '발표 시간 1팀당 몇 분이에요?',
      reply: null,
    },
    {
      id: 'q003',
      author: '미쉘',
      time: '20:50',
      body: '화장실 위치 알려주세요!',
      reply: {
        body: '같은 층 엘리베이터 옆에 있어요!',
        time: '20:52',
      },
    },
    {
      id: 'q004',
      author: '재훈',
      time: '21:03',
      body: 'DB 연결할 때 어디서 connection string 발급받나요? Replit Postgres 처음 써봐요.',
      reply: null,
    },
    {
      id: 'q005',
      author: '지나',
      time: '21:18',
      body: '커피 더 마실 수 있나요?',
      reply: {
        body: '네! 입구 옆 바리스타님께 말씀해주세요 ☕',
        time: '21:19',
      },
    },
  ],

  // 사전 참석자 명단 (LUMA CSV에서 import한 mock — 매칭 키: 전화번호)
  attendees: [
    { name: '수아',  phone: '010-1234-0001', source: '공개모집', approved: true,  team: 'LATTE' },
    { name: '민지',  phone: '010-1234-0002', source: '공개모집', approved: true,  team: 'LATTE' },
    { name: '일렌',  phone: '010-1234-0003', source: '초대용',   approved: true,  team: 'BUILDLAB' },
    { name: '미쉘',  phone: '010-1234-0004', source: '초대용',   approved: true,  team: null },
    { name: '필',    phone: '010-1234-0005', source: '공개모집', approved: true,  team: 'DECAF' },
    { name: 'Sky',   phone: '010-1234-0006', source: '공개모집', approved: true,  team: 'PRISM' },
    { name: '재훈',  phone: '010-1234-0007', source: '공개모집', approved: true,  team: 'PRISM' },
    { name: '지나',  phone: '010-1234-0008', source: '초대용',   approved: true,  team: 'BRIM' },
    { name: '해리',  phone: '010-1234-0009', source: '공개모집', approved: true,  team: 'LOOPER' },
    { name: '진',    phone: '010-1234-0010', source: '공개모집', approved: true,  team: 'LOOPER' },
    { name: '보리',  phone: '010-1234-0011', source: '초대용',   approved: true,  team: 'SHIBA' },
    { name: '도윤',  phone: '010-1234-0012', source: '공개모집', approved: true,  team: 'NOTEBOX' },
    { name: '서아',  phone: '010-1234-0013', source: '공개모집', approved: true,  team: 'NOTEBOX' },
    { name: '영수',  phone: '010-1234-0014', source: '공개모집', approved: false, team: null },
    { name: '재이',  phone: '010-1234-0015', source: '초대용',   approved: true,  team: null },
    { name: '하늘',  phone: '010-1234-0016', source: '공개모집', approved: true,  team: null },
    { name: '준호',  phone: '010-1234-0017', source: '초대용',   approved: false, team: null },
  ],
};
