// REPL CLUB — Mock data (정적 데모용)
// 실서비스 전환 시 백엔드 API로 교체 예정.

window.RC_DATA = {
  config: {
    eventDate: '2026.05.08 (FRI)',
    venue: '해시드 20층',
    deadline: '21:45',
    sosPhone: '010-0000-0000',
    wifi: { ssid: 'HASHED-GUEST', pw: 'replclub2026' },
    awards: { gold: 1, silver: 1, bronze: 3, passed: 6 },
  },

  // 시상 단계 공개 상태 (어드민 단계별 공개 시뮬레이션)
  // 'hidden' | 'passed' | 'bronze' | 'silver' | 'gold'
  awardPhase: 'hidden',

  projects: [
    {
      id: 'p001',
      team: 'LATTE',
      tagline: '카페 사장이 매출 데이터를 말로 분석하는 도구',
      members: ['수아', '민지'],
      url: 'https://latte.replit.app',
      registeredAt: '20:14',
      comments: 3,
      award: null, // 'gold' | 'silver' | 'bronze' | 'passed' | null
      details: {
        problem: '소규모 카페 사장님들은 POS·배달앱·SNS 데이터가 흩어져 있어 한 번에 보기 어렵습니다. 매출 패턴 파악에 매주 2시간씩 들어가요.',
        target: '동네 카페 사장님 (1~2인 운영, 대시보드 도구는 부담스러운 분).',
        better: '엑셀·차트 만들지 않고 "지난주 대비 어떠냐"고 말로 묻기만 하면 답이 옵니다. 이상치도 자동으로 알려줘요.',
        mvp: '4시간 안에 — POS CSV 업로드 + 자연어 질문 + 핵심 지표 자동 답변. 배포까지.',
        progress: 'POS CSV 업로드 → 매출/원가/마진 자동 계산까지 작동. 자연어 질문은 GPT-4 호출 붙임.',
      },
    },
    {
      id: 'p002',
      team: 'BUILDLAB',
      tagline: '사내 회의 자동 요약 + 액션아이템 추출 봇',
      members: ['일렌'],
      url: 'https://buildlab.replit.app',
      registeredAt: '20:08',
      comments: 1,
      award: null,
      details: {
        problem: '회의 끝나면 모두 "정리해서 공유"라고 말만 하고 안 합니다. 액션아이템이 사라지는 게 가장 큰 손실.',
        target: '회의 많은 팀 (PM·디자이너·엔지니어 5인 이상).',
        better: 'Slack에 봇이 들어가서 회의 노트 붙이면 1분 안에 요약·액션아이템·담당자 추출.',
        mvp: '회의 텍스트 입력 → 요약 + 액션아이템 카드 출력 + 담당자 멘션.',
        progress: '입력·요약 작동. Slack 연동은 webhook까지.',
      },
    },
    {
      id: 'p003',
      team: 'DECAF',
      tagline: '매일 아침 회고를 5분 안에 끝내는 자동 정리 도구',
      members: ['미쉘', '필'],
      url: 'https://decaf.replit.app',
      registeredAt: '19:55',
      comments: 5,
      award: null,
      details: {
        problem: '회고 안 합니다. 시간 없고 양식도 매번 헷갈려서.',
        target: '주니어 ~ 미들 PM·기획자, 매일 회고하고 싶지만 못하는 분.',
        better: '오늘 한 일·내일 할 일·막힌 점만 음성으로 말하면 자동으로 정리·아카이빙.',
        mvp: '음성 입력 → 자동 분류 → 기록 + 주간 리뷰 자동 생성.',
        progress: '음성 → 텍스트 + 분류까지. 주간 리뷰는 mock UI.',
      },
    },
    {
      id: 'p004',
      team: 'PRISM',
      tagline: '프롬프트 변형 A/B 테스트 자동화 워크벤치',
      members: ['Sky', '재훈'],
      url: 'https://prism.replit.app',
      registeredAt: '20:35',
      comments: 2,
      award: null,
      details: {
        problem: '프롬프트 엔지니어링하면 변형 5~10개 만들고 손으로 비교. 너무 비효율.',
        target: 'AI 제품 만드는 개발자·PM.',
        better: '프롬프트 템플릿 입력 → 변형 자동 생성 → 동일 데이터셋 batch 평가 → 표로 비교.',
        mvp: '프롬프트 입력 → 변형 5개 생성 → 평가 → 결과 비교 테이블.',
        progress: '변형 생성·평가 작동. 결과 시각화는 단순 테이블.',
      },
    },
    {
      id: 'p005',
      team: 'BRIM',
      tagline: '이메일 답장 톤 가이드: 친절/단호/유머 자동 변환',
      members: ['지나'],
      url: 'https://brim.replit.app',
      registeredAt: '20:22',
      comments: 4,
      award: null,
      details: {
        problem: '이메일 톤 잡기 어렵습니다. 너무 딱딱하거나 너무 친절하거나.',
        target: '대외 커뮤니케이션 많은 직군 (영업·CS·PR).',
        better: '초안 입력 → 3가지 톤(친절/단호/유머) 자동 생성 → 클릭 한 번에 적용.',
        mvp: '초안 → 3톤 변환 → 복사.',
        progress: '변환·복사까지 작동. 메일 클라이언트 연동은 mock.',
      },
    },
    {
      id: 'p006',
      team: 'LOOPER',
      tagline: '주간 KPI 대시보드 자동 생성 (Slack DM 발송)',
      members: ['해리', '진'],
      url: 'https://looper.replit.app',
      registeredAt: '20:51',
      comments: 0,
      award: null,
      details: {
        problem: '주간 KPI 대시보드 사람이 매주 만들어요. 시간 낭비.',
        target: '데이터 인프라 갖춘 스타트업.',
        better: 'GA4·Mixpanel 연결 → 매주 월요일 9시에 Slack DM으로 자동 발송.',
        mvp: 'Mock 데이터 기준 대시보드 생성 + Slack 발송 시뮬레이션.',
        progress: '대시보드 생성·Slack 발송 작동.',
      },
    },
    {
      id: 'p007',
      team: 'SHIBA',
      tagline: '강아지 산책 코스 추천 앱 (반려동물 PM의 부캐)',
      members: ['보리'],
      url: 'https://shiba.replit.app',
      registeredAt: '20:42',
      comments: 7,
      award: null,
      details: {
        problem: '매일 같은 산책 코스 지겨워요. 강아지도 사람도.',
        target: '서울 사는 반려인.',
        better: '주변 1km 내 새 코스 + 다른 반려인 인기 코스 + 날씨 반영 추천.',
        mvp: '내 위치 → 추천 3코스 + 즐겨찾기.',
        progress: '위치 기반 추천·즐겨찾기 작동.',
      },
    },
    {
      id: 'p008',
      team: 'NOTEBOX',
      tagline: '메모를 GPT에게 던지면 카드 형태로 정리',
      members: ['도윤', '서아'],
      url: 'https://notebox.replit.app',
      registeredAt: '21:02',
      comments: 1,
      award: null,
      details: {
        problem: '메모 적어두지만 다시 안 봐요. 검색·분류 귀찮음.',
        target: '아이디어 메모 많이 하는 직장인·학생.',
        better: '메모 던지면 GPT가 분류·요약·태그·카드화 → 자동 인덱스.',
        mvp: '입력 → 분류·태그 → 카드 보드.',
        progress: '입력·카드화 작동.',
      },
    },
  ],

  qa: [
    {
      id: 'q001',
      author: '수아',
      time: '20:33',
      body: 'Replit 크레딧 어디서 받아요?',
      reply: {
        body: '체크인 데스크에서 받으셨던 카드 뒷면에 코드 적혀있어요! Replit 로그인 후 입력해 주세요 🙏',
        time: '20:35',
      },
    },
    {
      id: 'q002',
      author: '일렌',
      time: '20:41',
      body: '발표 시간 1팀당 몇 분이에요?',
      reply: null,
    },
    {
      id: 'q003',
      author: '미쉘',
      time: '20:50',
      body: '화장실 위치 알려주세요!',
      reply: {
        body: '같은 층 엘리베이터 옆에 있어요!',
        time: '20:52',
      },
    },
    {
      id: 'q004',
      author: '재훈',
      time: '21:03',
      body: 'DB 연결할 때 어디서 connection string 발급받나요? Replit Postgres 처음 써봐요.',
      reply: null,
    },
    {
      id: 'q005',
      author: '지나',
      time: '21:18',
      body: '커피 더 마실 수 있나요?',
      reply: {
        body: '네! 입구 옆 바리스타님께 말씀해주세요 ☕',
        time: '21:19',
      },
    },
  ],

  // 사전 참석자 명단 (LUMA CSV에서 import한 mock)
  attendees: [
    { name: '수아',  email: 'sua@~',       source: '공개모집', approved: true,  team: 'LATTE' },
    { name: '민지',  email: 'minji@~',     source: '공개모집', approved: true,  team: 'LATTE' },
    { name: '일렌',  email: 'ellen@~',     source: '초대용',   approved: true,  team: 'BUILDLAB' },
    { name: '미쉘',  email: 'michelle@~',  source: '초대용',   approved: true,  team: null },
    { name: '필',    email: 'feel@~',      source: '공개모집', approved: true,  team: 'DECAF' },
    { name: 'Sky',  email: 'sky@~',       source: '공개모집', approved: true,  team: 'PRISM' },
    { name: '재훈',  email: 'jh@~',        source: '공개모집', approved: true,  team: 'PRISM' },
    { name: '지나',  email: 'jina@~',      source: '초대용',   approved: true,  team: 'BRIM' },
    { name: '해리',  email: 'harry@~',     source: '공개모집', approved: true,  team: 'LOOPER' },
    { name: '진',    email: 'jin@~',       source: '공개모집', approved: true,  team: 'LOOPER' },
    { name: '보리',  email: 'bori@~',      source: '초대용',   approved: true,  team: 'SHIBA' },
    { name: '도윤',  email: 'doyun@~',     source: '공개모집', approved: true,  team: 'NOTEBOX' },
    { name: '서아',  email: 'seoa@~',      source: '공개모집', approved: true,  team: 'NOTEBOX' },
    { name: '영수',  email: 'ys@~',        source: '공개모집', approved: false, team: null },
    { name: '재이',  email: 'jaei@~',      source: '초대용',   approved: true,  team: null },
    { name: '하늘',  email: 'haneul@~',    source: '공개모집', approved: true,  team: null },
    { name: '준호',  email: 'junho@~',     source: '초대용',   approved: false, team: null },
  ],
};
